/**
 * @file Platform.h
 * @author Kexuan Zhang (zzxzzk115@gmail.com)
 * @brief
 * @version 0.1.0
 * @date 2023-11-28
 *
 * @copyright Copyright (c) 2023
 *
 */

#pragma once

#define SOME_ENGINE_PLATFORM_EMSCRIPTEN 0
#define SOME_ENGINE_PLATFORM_ANDROID 0
#define SOME_ENGINE_PLATFORM_IOS 0
#define SOME_ENGINE_PLATFORM_DARWIN 0
#define SOME_ENGINE_PLATFORM_LINUX 0
#define SOME_ENGINE_PLATFORM_WINDOWS 0
#define SOME_ENGINE_PLATFORM_RPI_32 0 // Raspberry Pi 0-3
#define SOME_ENGINE_PLATFORM_RPI_64 0 // Raspberry Pi 4+ CM4+
#define SOME_ENGINE_PLATFORM_SWITCH 0
#define SOME_ENGINE_PLATFORM_PS4 0
#define SOME_ENGINE_PLATFORM_PS5 0
#define SOME_ENGINE_PLATFORM_XBOX_ONE 0
#define SOME_ENGINE_PLATFORM_XBOX_X 0

#if defined(BUILD_EMSCRIPTEN) || defined(__EMSCRIPTEN__) || defined(__wasm__) || defined(__wasm32__) || defined(__wasm64__)
#undef SOME_ENGINE_PLATFORM_EMSCRIPTEN
#define SOME_ENGINE_PLATFORM_EMSCRIPTEN 1
#elif defined(BUILD_ANDROID) || defined(__ANDROID__)
#undef SOME_ENGINE_PLATFORM_ANDROID
#define SOME_ENGINE_PLATFORM_ANDROID 1
#elif defined(__APPLE__) && defined(__arm__)
#undef SOME_ENGINE_PLATFORM_IOS
#define SOME_ENGINE_PLATFORM_IOS 1
#elif defined(__APPLE__) && defined(__MACH__)
#undef SOME_ENGINE_PLATFORM_DARWIN
#define SOME_ENGINE_PLATFORM_DARWIN 1
#elif defined(__linux__)
#undef SOME_ENGINE_PLATFORM_LINUX
#define SOME_ENGINE_PLATFORM_LINUX 1
#if defined(__arm__) && !defined(__aarch64__) // Raspberry Pi and other embed linux arm devices
#undef SOME_ENGINE_PLATFORM_RPI_32
#define SOME_ENGINE_PLATFORM_RPI_32 1
#else
#undef SOME_ENGINE_PLATFORM_RPI_64
#define SOME_ENGINE_PLATFORM_RPI_64 1
#endif
#elif defined(_WIN32) || defined(_WIN64)
#undef SOME_ENGINE_PLATFORM_WINDOWS
#define SOME_ENGINE_PLATFORM_WINDOWS 1
#elif defined(__SWITCH__)
#undef SOME_ENGINE_PLATFORM_SWITCH
#define SOME_ENGINE_PLATFORM_SWITCH 1
#elif defined(__ORBIS__) // PS4
#undef SOME_ENGINE_PLATFORM_PS4
#define SOME_ENGINE_PLATFORM_PS4 1
#elif defined(__PS5__)
#undef SOME_ENGINE_PLATFORM_PS5
#define SOME_ENGINE_PLATFORM_PS5 1
#elif defined(_XBOX_ONE)
#undef SOME_ENGINE_PLATFORM_XBOX_ONE
#define SOME_ENGINE_PLATFORM_XBOX_ONE 1
#elif defined(_XBOX_SERIES_X)
#undef SOME_ENGINE_PLATFORM_XBOX_X
#define SOME_ENGINE_PLATFORM_XBOX_X 1
#else
#error "Unsupported Platform"
#endif

#if SOME_ENGINE_PLATFORM_RPI_32 || SOME_ENGINE_PLATFORM_RPI_64
#undef SOME_ENGINE_PLATFORM_RPI
#define SOME_ENGINE_PLATFORM_RPI 1
#endif

#define SOME_ENGINE_PLATFORM_WEB 0
#define SOME_ENGINE_PLATFORM_MOBILE 0
#define SOME_ENGINE_PLATFORM_DESKTOP 0
#define SOME_ENGINE_PLATFORM_GAME_CONSOLE 0

#if SOME_ENGINE_PLATFORM_EMSCRIPTEN
#undef SOME_ENGINE_PLATFORM_WEB
#define SOME_ENGINE_PLATFORM_WEB 1
#elif SOME_ENGINE_PLATFORM_ANDROID || SOME_ENGINE_PLATFORM_IOS
#undef SOME_ENGINE_PLATFORM_MOBILE
#define SOME_ENGINE_PLATFORM_MOBILE 1
#elif SOME_ENGINE_PLATFORM_DARWIN || SOME_ENGINE_PLATFORM_LINUX || SOME_ENGINE_PLATFORM_WINDOWS
#undef SOME_ENGINE_PLATFORM_DESKTOP
#define SOME_ENGINE_PLATFORM_DESKTOP 1
#elif SOME_ENGINE_PLATFORM_SWITCH || SOME_ENGINE_PLATFORM_PS4 || SOME_ENGINE_PLATFORM_PS5 || SOME_ENGINE_PLATFORM_XBOX_ONE || SOME_ENGINE_PLATFORM_XBOX_X
#undef SOME_ENGINE_PLATFORM_GAME_CONSOLE
#define SOME_ENGINE_PLATFORM_GAME_CONSOLE 1
#endif

#define SOME_ENGINE_WINDOW_ABSTRACT_GLFW 0
#define SOME_ENGINE_WINDOW_ABSTRACT_SDL 0
#define SOME_ENGINE_WINDOW_ABSTRACT_EGL 0

#if defined(USE_WINDOW_ABSTRACT_GLFW) // User configured GLFW
#undef SOME_ENGINE_WINDOW_ABSTRACT_GLFW
#define SOME_ENGINE_WINDOW_ABSTRACT_GLFW 1
#elif defined(USE_WINDOW_ABSTRACT_SDL) // User configured SDL
#undef SOME_ENGINE_WINDOW_ABSTRACT_SDL
#define SOME_ENGINE_WINDOW_ABSTRACT_SDL 1
#elif defined(SOME_ENGINE_WINDOW_ABSTRACT_EGL)
#undef SOME_ENGINE_WINDOW_ABSTRACT_EGL
#define SOME_ENGINE_WINDOW_ABSTRACT_EGL 1
#else // Default settings
#if SOME_ENGINE_PLATFORM_DESKTOP
#undef SOME_ENGINE_WINDOW_ABSTRACT_GLFW
#define SOME_ENGINE_WINDOW_ABSTRACT_GLFW 1
#elif SOME_ENGINE_PLATFORM_MOBILE || SOME_ENGINE_PLATFORM_WEB || SOME_ENGINE_PLATFORM_GAME_CONSOLE
#undef SOME_ENGINE_WINDOW_ABSTRACT_SDL
#define SOME_ENGINE_WINDOW_ABSTRACT_SDL 1
#endif
#endif

#define SOME_ENGINE_RENDER_API_OPENGL 0
#define SOME_ENGINE_RENDER_API_OPENGLES 0

// Default OpenGL/ES versions
#define SOME_ENGINE_RENDER_API_OPENGL_MIN_MAJOR 3
#define SOME_ENGINE_RENDER_API_OPENGL_MIN_MINOR 3
#define SOME_ENGINE_RENDER_API_OPENGLES_MIN_MAJOR 3
#define SOME_ENGINE_RENDER_API_OPENGLES_MIN_MINOR 0

#if SOME_ENGINE_PLATFORM_DESKTOP
#undef SOME_ENGINE_RENDER_API_OPENGL
#define SOME_ENGINE_RENDER_API_OPENGL 1
#if SOME_ENGINE_PLATFORM_RPI_64 // OpenGLES 3.0 on RPI4+, CM4+
#undef SOME_ENGINE_RENDER_API_OPENGL
#undef SOME_ENGINE_RENDER_API_OPENGLES
#define SOME_ENGINE_RENDER_API_OPENGLES 1
#undef SOME_ENGINE_RENDER_API_OPENGLES_MIN_MAJOR
#define SOME_ENGINE_RENDER_API_OPENGLES_MIN_MAJOR 3
#undef SOME_ENGINE_RENDER_API_OPENGLES_MIN_MINOR
#define SOME_ENGINE_RENDER_API_OPENGLES_MIN_MINOR 0
#elif SOME_ENGINE_PLATFORM_RPI_32 // OpenGLES 2.0 on RPI0-3
#undef SOME_ENGINE_RENDER_API_OPENGL
#undef SOME_ENGINE_RENDER_API_OPENGLES
#define SOME_ENGINE_RENDER_API_OPENGLES 1
#undef SOME_ENGINE_RENDER_API_OPENGLES_MIN_MAJOR
#define SOME_ENGINE_RENDER_API_OPENGLES_MIN_MAJOR 2
#undef SOME_ENGINE_RENDER_API_OPENGLES_MIN_MINOR
#define SOME_ENGINE_RENDER_API_OPENGLES_MIN_MINOR 0
#endif
#elif SOME_ENGINE_PLATFORM_MOBILE || SOME_ENGINE_PLATFORM_WEB || SOME_ENGINE_PLATFORM_GAME_CONSOLE
#undef SOME_ENGINE_RENDER_API_OPENGLES
#define SOME_ENGINE_RENDER_API_OPENGLES 1
#endif

#define SOME_ENGINE_GUI_IMPL_IMGUI 1 // Currently, only use imgui